[workspace]
channels = ["conda-forge"]
name = "graphs"
platforms = ["osx-arm64", "linux-64", "win-64"]
version = "0.1.0"

[tasks]

[dependencies]
tsplib95 = ">=0.7.1,<0.8"
numpy = ">=2.3.3,<3"
scipy = ">=1.16.2,<2"
